Homework8 is done.
BogovarovaV/valentina-b pull request #8
Opened 2021-11-02 19:08 UTC by BogovarovaV

2021-11-02 22:06 UTC, OKrylov approved these changes
По заданиям все отлично, по коду и логике все выполнено корректно.
оставил небольшое замечание по наименованию метода

2021-11-02 22:06 UTC, OKrylov commented on src/pro/sky/java/cours1/homework8/Book.java
> +    public Author getAuthorName() {
данный метод возвращает целиком автора, а не только его имя, следует переименовать

2021-11-04 15:45 UTC, OKrylov requested changes
Массив создан корректно, метод по добавлению реализован верно. По методу печати есть замечание

2021-11-04 15:45 UTC, OKrylov commented on src/pro/sky/java/cours1/homework8/Homework8.java
> +            break;
почему break? Если мы хотим распечатать все книги, то тогда нужно идти по элементам массива в цикле и использовать вместо book `bookBox[i]`. При этом параметр метода `Book book` будет лишним

2021-11-04 15:52 UTC, BogovarovaV commented on src/pro/sky/java/cours1/homework8/Homework8.java
> +            break;
Я не знаю почему :( Я вообще плохо понимаю, что делать надо... Читаю-перечитываю, а в голове каша. Можно я тогда просто удалю задание среднего уровня и сделаю мерж, чтобы перейти к домашке следующего урока?

2021-11-09 16:11 UTC, merged